AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for ECS Fargate service, SNS topic, and CloudWatch alarm with event rule.

Parameters:

  SNSTopicArn:
    Type: String
    Description: Name of the SNS Topic ARN
    Default: "arn:aws:sns:eu-central-1:891377259916:REMACloudWatchAlarms"
  SNSTopicName:
    Type: String
    Description: Name of the SNS Topic
    Default: "REMACloudWatchAlarms"
  PhoneNumber:
    Type: String
    Description: Phone number for SMS subscription (in E.164 format, e.g., +1234567890)
    Default: "007"
  ECSClusterArn:
    Type: String
    Description: ECS Cluster ARN
    Default: "arn:aws:ecs:eu-central-1:891377259916:cluster/vigo-cluster"
  ECSClusterName:
    Type: String
    Description: ECS Cluster Name
    Default: vigo-cluster
  FargateServiceName:
    Type: String
    Description: Fargate Service Name
    Default: rema1000dk
  TaskThreshold:
    Type: Number
    Description: Task count threshold, when to receive an alarm notification.
    Default: 4


Resources:

  TaskCloudWatchCountAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref SNSTopicArn
      ComparisonOperator: GreaterThanThreshold
      DatapointsToAlarm: 1
      Dimensions:
        - Name: ClusterName
          Value: !Ref ECSClusterName
        - Name: ServiceName
          Value: !Ref FargateServiceName
      EvaluationPeriods: 1
      MetricName: RunningTaskCount
      Namespace: AWS/ECS
      Period: 300
      Statistic: Average
      Threshold: !Ref TaskThreshold

  # SNS Subscription
  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SNSTopicArn
      Protocol: SMS
      Endpoint: !Ref PhoneNumber
  AlarmTopicPolicy309DB5F8:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action: [
              "SNS:Publish",
              "SNS:GetTopicAttributes",
              "SNS:SetTopicAttributes",
            ]
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Resource: !Ref SNSTopicArn
            Sid: '0'
        Version: '2012-10-17'
      Topics:
        - !Ref SNSTopicArn

  # Event Rule
  ECSTaskStateChangeRule:
    Type: AWS::Events::Rule
    Properties:
      Name: ECSTaskStateChangeRule
      EventPattern:
        source:
          - "aws.ecs"
        detail-type:
          - "ECS Task State including RUNNING"
        detail:
          clusterArn:
            - !Ref ECSClusterArn
          lastStatus:
            - "RUNNING"
          desiredStatus:
            - "RUNNING"
      Targets:
        - Arn: !Ref SNSTopicArn
          Id: "ECSTaskStateChangeRuleTarget"
          Input: !Join
            - ''
            - - '"Tasks count for '
              - !Ref FargateServiceName
              - ' is increasing..."'
Outputs:
  ECSClusterName:
    Description: Name of the ECS Cluster
    Value: !Ref ECSClusterName
  FargateServiceName:
    Description: Name of the ECS Fargate Service
    Value: !Ref FargateServiceName
  SNSTopicName:
    Description: Name of the SNS Topic
    Value: !Ref SNSTopicName
  PhoneNumber:
    Description: Phone number for SMS subscription
    Value: !Ref PhoneNumber